using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BookOrGetBooked.Shared.DTOs
{
    public class BookingResponseDTO
    {
        public int Id { get; set; }  // Auto-generated by the database
        public int UserId { get; set; }
        public int ServiceId { get; set; }
        public DateTime TimeSlot { get; set; }
        public required string Status { get; set; }  // Status (e.g., Pending, Confirmed, etc.)
    }
}
